INSERT INTO roles (role) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT role FROM roles WHERE role = 'ROLE_ADMIN');

INSERT INTO roles (role) SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT role FROM roles WHERE role = 'ROLE_USER');

INSERT INTO roles (role) SELECT 'ROLE_CREATOR' WHERE NOT EXISTS (SELECT role FROM roles WHERE role = 'ROLE_CREATOR');

INSERT INTO roles (role) SELECT 'ROLE_LEARNER' WHERE NOT EXISTS (SELECT role FROM roles WHERE role = 'ROLE_LEARNER');
